### ISSUE TITLE
One function is not defined

### ISSUE THREAD

**Issue by cdqu** [schroederdewitt/multiagent_mujoco#1]
I tried to run 'mujoco_multi.py' on Ubuntu 18.04.  But I have found that one function in **mujoco_multi.py line 219**, which is **get_nearest_obs()**, is not defined and the program failed. Could you please give the definition? 
Thank you very much!

**Comment by schroederdewitt** [comment]
Hi, thanks for raising this issue! The code at the bottom of _src/multiagent_mujoco/mujoco_multi.py_ is outdated and I have just removed it. If you are wondering how to use Multi-Agent Mujoco, please have a look at the readme. If you want to extend it with new scenarios, please have a look at the existing scenario definitions in _src/multiagent_mujoco/obsk.py_ . If you get stuck, please do not hesitate to contact me again! Many thanks. Christian
