### ISSUE TITLE
ModuleNotFoundError: No module named 'envs'

### ISSUE THREAD

**Issue by yeshenpy** [schroederdewitt/multiagent_mujoco#11]
> Traceback (most recent call last):
  File "run_maxminMADDPG.py", line 227, in <module>
    env = MujocoMulti(env_args=CONFIG[args.env_name])
  File "/home/wangcong/MARL/src/multiagent_mujoco/mujoco_multi.py", line 82, in __init__
    from envs import REGISTRY as env_REGISTRY
Any advice about this issue?

Best wishes.

**Comment by schroederdewitt** [comment]
Hi, can you post the env_args you are using? Cheers!

**Comment by yeshenpy** [comment]
I have solved the problem, some env information is missing from the folder. But I still have some questions. After testing, the dimension of obs of manyagent_ant is 150?  Why is it so large?

**Comment by whynot-s** [comment]
> I have solved the problem, some env information is missing from the folder. But I still have some questions. After testing, the dimension of obs of manyagent_ant is 150? Why is it so large?

Hi, may I ask how you solved the problem? I have encountered the same error while running the many-agent-swimmer. Thanks :) @yeshenpy

**Comment by yeshenpy** [comment]
@whynot-s  you need to copy the file from the comix project provided by the original paper.  rename the file as the comix project
 and add the file.

**Comment by HaoshengZou** [comment]
I've provided a minimal fix for this #12 .

**Comment by schroederdewitt** [comment]
Thanks a lot for this fix, Haosheng, which I have just merged back into the repository. It turned out I had failed to push the latest project version to the repo, but your changes are a bit more precise so I have kept yours. Thanks again!
