### ISSUE TITLE
Configure the environment

### ISSUE THREAD

**Issue by yeshenpy** [schroederdewitt/multiagent_mujoco#2]
I am very interested in the multi-agent mujoco you posted on github, but the file that guides the configuration environment is only one sentence, whether you can provide a detailed configuration file, it will be a great help, thank you very much.

**Comment by schroederdewitt** [comment]
Hi Yeshenpy, many thanks for raising this issue. Are you wanting to run an in-built scenario, or are you wanting to create a new one? I am happy to help either way, but the answer would look differently so please let me know what you are up to :)

**Comment by yeshenpy** [comment]
Hi, dear schroederdewitt:
thank you very much for your reply. I just want to run an in-built scenario
shown on the picture in the paper, and I hope to get your guidance.
Thanks again .

**Comment by schroederdewitt** [comment]
Hi @yeshenpy, you need to create a Multiagent-Mujoco instance defined 
[here](https://github.com/schroederdewitt/multiagent_mujoco/blob/master/src/multiagent_mujoco/mujoco_multi.py
)
The README tells you which parameters to set for the different scenarios: 
[here](https://github.com/schroederdewitt/multiagent_mujoco/blob/master/README.md)

If you are interested in how the agent models are defined, have a look at obsk.py:
[here](https://github.com/schroederdewitt/multiagent_mujoco/blob/master/src/multiagent_mujoco/obsk.py)

Does any of this help? Do you have a more specific question I can answer? Many thanks! C.

**Comment by yeshenpy** [comment]
Sorry for my late reply .I still have some questions :
 What is the version of Mujoco and mujoco_py?  I also found many packages that were not included during the configuration process and could not be imported. such as 
`from utils.dict2namedtuple import convert`
Many thanks .

**Comment by yeshenpy** [comment]
There is one more request, could you please provide a simple running demo,
which may be more helpful, thanks again.

>

**Comment by schroederdewitt** [comment]
Many thanks for your reply - it's Mujoco 2.0 and I have added an example to the [Readme](https://github.com/schroederdewitt/multiagent_mujoco/blob/master/README.md). Please let me know if it works now!

**Comment by yeshenpy** [comment]
Thank you very much for your help. It works. Thanks again！！！！！If there is any problem, I may trouble you again later. Thank you.
