### ISSUE TITLE
`env.render(mode='rgb_array')` returns `none`

### ISSUE THREAD

**Issue by fyqqyf** [schroederdewitt/multiagent_mujoco#25]
My question is as stated in the title, I look forward to your answer.
Thanks!

**Comment by fyqqyf** [comment]
The problem is solved, and I modified the `render()` function in file `mujoco_multi.py` as follows.
`def render(self, **kwargs):
     return self.env.render(**kwargs)`
However, I’m not sure if this will cause any more issues. Can anyone help me with this question?

**Comment by 51616** [comment]
related to #13
