### ISSUE TITLE
Bug for Humanoid-v2

### ISSUE THREAD

**Issue by parachutel** [schroederdewitt/multiagent_mujoco#5]
For 2-Agent Humanoid-v2, the `action_space` defined in `MujocoMulti.__init__` is `(Box(8,), Box(8,))`, with a flat dim of 16. However, the underlying original mujoco env `MujocoMulti.wrapped_env` has an action space of `Box(17,)`. There is a mismatch in flat action dims.

**Comment by schroederdewitt** [comment]
Dear @parachutel, many thanks for raising this issue. I have just pushed a fix for scenarios with unequal agent action dimensions. Please note that the config for Humanoid/Humanoid-Standup has changed slightly:


### 2-Agent Humanoid

```python
env_args.scenario="Humanoid-v2"
env_args.agent_conf="9|8"
env_args.agent_obsk=1
```

### 2-Agent HumanoidStandup

```python
env_args.scenario="HumanoidStandup-v2"
env_args.agent_conf="9|8"
env_args.agent_obsk=1
