### ISSUE TITLE
2-Agent Walker

### ISSUE THREAD

**Issue by Baichengchaofire** [schroederdewitt/multiagent_mujoco#6]
env_args.scenario = "Walker2d-v2"
env_args.agent = "2x3"

**Comment by schroederdewitt** [comment]
Dear @Baichengchaofire, I have tested the following configuration:

```python3
env_args.scenario="Walker2d-v2" 
env_args.agent_conf="2x3"
```

and it ran just fine. Do you have any description of what went wrong for you?

**Comment by schroederdewitt** [comment]
assuming this was addressed by [Issue #3](https://github.com/schroederdewitt/multiagent_mujoco/issues/3)

**Comment by Baichengchaofire** [comment]
I mean the name of the scenario and the configuration of the agent_conf are not the same as those listed in your previous task configuration file. Now you have changed it.
