### ISSUE TITLE
Bug in mujoco_multi.py?

### ISSUE THREAD

**Issue by SigmaBM** [schroederdewitt/multiagent_mujoco#7]
[Line 55](https://github.com/schroederdewitt/multiagent_mujoco/blob/308772baf1e5cac14e64cbb889d0a3c51857c36b/src/multiagent_mujoco/mujoco_multi.py#L55) of `mujoco_multi.py`. Should `if` here be `elif`?

**Comment by schroederdewitt** [comment]
Yes, thanks for spotting!
