### ISSUE TITLE
Meaning of variables in the environment

### ISSUE THREAD

**Issue by yeshenpy** [schroederdewitt/multiagent_mujoco#9]
Thank you very much for your benchmark. Here I have some questions to ask:
The specific meaning of the state. For example in 2-agent HalfCheetah,
[https://github.com/openai/gym/blob/master/gym/envs/mujoco/assets/half_cheetah.xml](url)
the state has 17 dimensions. Each agent's obs has 6 dimensions. There are still 5 dimensions in the state.
Although looking at the official XML,  I still don't know exactly what these 5 dimensions mean. 
Hope to get your reply, Thanks.

**Comment by schroederdewitt** [comment]
Hi, many thanks for your question. Entries 0-2 correspond to global x,y,z position and the subsequent 2 encode global planar velocity.

**Comment by yeshenpy** [comment]
Thanks for your reply.  Actually, I have a little question about the position of x,y,z.   I trained an agent to get about 3000 rewards, .Velocity and position are recorded. (The index of 0,1,8,9,10 of state) 
![image](https://user-images.githubusercontent.com/43668853/109382022-c10d9180-7918-11eb-8bec-71f2532bb926.png)
![image](https://user-images.githubusercontent.com/43668853/109382031-d1be0780-7918-11eb-87a0-dbae6a959283.png)
![image](https://user-images.githubusercontent.com/43668853/109382037-dedaf680-7918-11eb-8b5f-f71e0ee397f9.png)
![image](https://user-images.githubusercontent.com/43668853/109382041-ebf7e580-7918-11eb-9209-04c612fe3383.png)
![image](https://user-images.githubusercontent.com/43668853/109382044-f619e400-7918-11eb-834c-b1e4b923ab2c.png)
Where the first two figures are about the velocities, the last three figures are the position of x,y,z. Intuitively, if the velocity is positive, then the position should be monotonically increasing. But as the figure above shows, the results are not as expected. Could there be some explanation for this?
